In [25]:
import sys
sys.path.append("/kaggle/input")

FIS model

In [26]:
def FIS(Turn = None,filePath='./data/Dataset/Meta_result_txl.csv',fileName=None,cluster = []):
    import numpy as np
    import pandas as pd
    from module.Rules_Function.RuleWeight import RuleWeight
    import seaborn as sns
    import matplotlib.pyplot as plt
    from module.Rules_Function.Rules_gen import rule_generate
    from module.Rules_Function.Rules_reduce import reduce_rule,remove_rule
    import pickle
    from module.Convert.var_lang import change_var_lang̣,change_var_lang̣_default
    import sys
    import time
    import os

    base_dir = "/kaggle/working/"
    input_dir = os.path.join(base_dir,f"data/FIS/input/{fileName}/")
    output_dir = os.path.join(base_dir,f"data/FIS/output/{fileName}/")
    output_dir_frb = os.path.join(base_dir,f"data/FIS/output/{fileName}/FRB/")

    if not os.path.exists(input_dir):
        os.makedirs(input_dir)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    if not os.path.exists(output_dir_frb):
        os.makedirs(output_dir_frb)
    start_time = time.time()
    

        
    df = pd.read_csv(filePath)

    full_data = df

    df_full_data = pd.DataFrame(full_data)
    train_data = df_full_data.sample(frac=0.8, random_state=None)
    train_data.to_csv(os.path.join(base_dir,f'data/FIS/input/{fileName}/train_data.csv'))
    train_data = train_data.values
    test_data = df_full_data.sample(frac=0.2, random_state=None)
    # print(train_data.shape)


    full_data = np.array(full_data)
    train_data = np.array(train_data)

    min_vals = np.min(full_data, axis=0)
    max_vals = np.max(full_data, axis=0)

    min_vals_data = pd.DataFrame(min_vals)
    max_vals_data = pd.DataFrame(max_vals)
    min_vals_data.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/min_vals.csv"))
    max_vals_data.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/max_vals.csv"))
    test_data.to_csv(os.path.join(base_dir,f'data/FIS/input/{fileName}/test_data.csv'))

    h = train_data.shape[0]
    w = train_data.shape[1]
    
    lang2 = ["Low","High"]
    lang3 = ["Low","Medium","High"]
    lang5 = ["Very Low","Low","Medium","High","Very High"]

    m = 2
    esp = 0.01
    maxTest = 200

    rules,centers,U = rule_generate(h,w,train_data,cluster,min_vals,max_vals,m,esp,maxTest)

    col_num = train_data.shape[1] -1
    label = train_data[:, col_num]

    for j in range(h):
        rules[j, col_num] = np.argmax(U[j, :]) + 1

    [t, sigma_M] = RuleWeight(rules, train_data[:,:-1], cluster, centers)
    sigma_M = sigma_M.reshape(-1,1)
    sigma_M = sigma_M[:-1, :]

    sigma_M = np.hstack((sigma_M[:, [0]], sigma_M[:, [0]], sigma_M[:, [0]]))

    rules = np.hstack((rules, np.min(t, axis=1, keepdims=True), train_data[:, [col_num]]))

    df_Rule_List = pd.DataFrame(rules)
    df_Rule_List.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Rule_List_All.csv"), index=False)

    rules_reduce = reduce_rule(h,col_num,rules)
    df_Rule_List1 = pd.DataFrame(rules_reduce)
    df_Rule_List1.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Rule_List_reduce.csv"), index=False)

    ruleList = remove_rule(h,col_num,rules_reduce)
    ruleListLang = change_var_lang̣_default(cluster,ruleList)

    df_rule_lang = pd.DataFrame(ruleListLang)
    df_rule_lang.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Rule_List_Language.csv"),index=False)
    df_rule_lang.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/FRB.csv"),index=False)
    
    df_rule_30 = df_rule_lang.sample(frac=0.3,random_state=42)
    df_rule_70 = df_rule_lang.sample(frac=0.7,random_state=42)
    df_rule_30.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/FRB/TestDataRule.csv"),index=False)
    df_rule_70.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/FRB/TrainDataRule.csv"),index=False)
    
    df_Rule_List = pd.DataFrame(ruleList)
    df_Rule_List.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Rule_List.csv"), index=False)

    df_Sigma = pd.DataFrame(sigma_M)
    df_Sigma.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Sigma_M.csv"), index=False)

    df_Centers = pd.DataFrame(centers)
    df_Centers.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Centers.csv"), index=False)

    print("ruleList:",ruleList)
    print("sigma_M:", sigma_M)
    print("centers:", centers)
    model_data = {
        "ruleList": ruleList,
        "sigma_M": sigma_M,
        "centers": centers,
        "min_vals": min_vals,
        "max_vals": max_vals
    }
    totalTime = time.time() - start_time
    print("Train finish : ",totalTime)
    if not os.path.exists(os.path.join(base_dir,f"models/{fileName}/")):
        os.makedirs(os.path.join(base_dir,f"models/{fileName}/"))
    with open(os.path.join(base_dir,f"models/{fileName}/fuzzy_model.pkl"), "wb") as file:
        pickle.dump(model_data, file)
    # with open(os.path.join("/kaggle/input/",f"models/{fileName}/fuzzy_model.pkl"), "wb") as file:
    #     pickle.dump(model_data, file)
        
    FIS_Test_file(Modality = "Metadata-Image Fusion",Turn = Turn,fileName=fileName)
    totalTime = time.time() - start_time
    print("All finish : ",totalTime)

FIS Test file

In [27]:
def FIS_Test_file(Modality=None,Turn =None,fileName=None):
    import numpy as np
    from module.Membership_Function.GaussMF import GaussMF
    from models.load_model import load_model
    from module.Test.fuzzify_input import fuzzify_input
    from module.Test.match_rule import match_rule
    import pandas as pd
    from module.Test.Test import test_fis
    from sklearn.metrics import precision_score,f1_score,recall_score,accuracy_score, confusion_matrix
    import time
    import csv,os
    base_dir = "/kaggle/working/"
    startTime = time.time()
    predict_labels = []
    true_labels = []

    data = pd.read_csv(os.path.join(base_dir,f"data/FIS/input/{fileName}/test_data.csv"))
    print(os.path.join(base_dir,f"data/FIS/input/{fileName}/test_data.csv"))
    label_index = data.shape[1]-1
    for i,r in data.iterrows():
        true_labels.append(r.values[label_index])
        sample_input = r.values[1:label_index]
        predict_labels.append(test_fis(sample_input,fileName))
    true_labels = np.array(true_labels)
    predicted_labels = np.array(predict_labels)
    
    accuracy = accuracy_score(true_labels, predicted_labels)
    print(f"Độ chính xác: {accuracy:.2%}")
    precision = precision_score(true_labels, predicted_labels,average='macro')
    print(f"Độ đo precision: {precision:.2%}")
    f1 = f1_score(true_labels, predicted_labels,average='macro')
    print(f"Độ đo F1: {f1:.2%}")
    recall = recall_score(true_labels, predicted_labels,average='macro',zero_division=0)
    print(f"Độ đo Recall: {recall:.2%}")
    conf_matrix = confusion_matrix(true_labels, predicted_labels)
    print("Confusion matrix:\n")
    print(conf_matrix)
    


    
    csv_file = os.path.join(base_dir,f"data/Test/{fileName}/acc.csv")
    if(Turn!=None):
        with open(csv_file, mode="a", newline="", encoding="utf-8") as file:
            writer = csv.writer(file)
            if file.tell() == 0:
                writer.writerow(["id","Modality","models","Accuracy", "F1 Score", "Recall"])

            writer.writerow([Turn,Modality,"FIS",f"{accuracy:.2%}", f"{f1:.2%}", f"{recall:.2%}"])
    endTime = time.time() - startTime
    print("Test xong : ", endTime)
    
    results = {
        "Total Time": [endTime],
        "Test Accuracy": [accuracy],
        "Test Precision": [precision],
        "Test Recall": [recall],
        "Test F1": [f1],
    }
    dfData = pd.DataFrame(results)
    dfData.to_csv(os.path.join(base_dir,f"data/FIS/output/{fileName}/Results_FIS.csv"), index=False)


Only Image Feature

In [28]:
FIS(fileName="Only Image Feature",
    filePath="/kaggle/input/datasetfile/OnlyImageFeture.csv",
    cluster=[5,5,5,5,5,5,5,5,5,5,6])

ruleList: [[3. 3. 2. ... 2. 4. 3.]
 [2. 2. 3. ... 1. 3. 4.]
 [3. 3. 2. ... 1. 1. 3.]
 ...
 [1. 1. 5. ... 4. 4. 3.]
 [1. 1. 5. ... 5. 5. 5.]
 [2. 2. 4. ... 1. 5. 1.]]
sigma_M: [[3.0947477  3.0947477  3.0947477 ]
 [2.58707077 2.58707077 2.58707077]
 [2.45241942 2.45241942 2.45241942]
 [2.36371599 2.36371599 2.36371599]
 [2.85389086 2.85389086 2.85389086]
 [2.53065254 2.53065254 2.53065254]
 [2.23304799 2.23304799 2.23304799]
 [4.12761883 4.12761883 4.12761883]
 [2.51166826 2.51166826 2.51166826]]
centers: [array([0.0362073 , 0.10554975, 0.22629384, 0.38376497, 0.76496469]), array([0.07864674, 0.16847464, 0.28595448, 0.45288485, 0.68785535]), array([0.32401927, 0.52058166, 0.6783481 , 0.80058245, 0.90151991]), array([0.19803404, 0.31659011, 0.4283054 , 0.55918099, 0.75464662]), array([0.27645473, 0.59005601, 0.75528528, 0.86750453, 0.94849467]), array([0.10472953, 0.19830537, 0.30125667, 0.44170784, 0.70065267]), array([0.02143816, 0.09048275, 0.1865597 , 0.31676611, 0.54728078]), array([

Only Table Feature Remove Missing

In [29]:
FIS(fileName="Only Table Feature Remove Missing",
    filePath="/kaggle/input/datasetfile/OnlyTableFeatureRemoveMissing.csv",
    cluster=[3,5,2,3,2,3,2,2,2,6])

ruleList: [[2. 1. 1. ... 2. 1. 5.]
 [1. 1. 1. ... 1. 1. 5.]
 [1. 4. 2. ... 2. 2. 1.]
 ...
 [2. 3. 2. ... 2. 2. 1.]
 [1. 2. 1. ... 1. 2. 1.]
 [3. 1. 2. ... 2. 2. 1.]]
sigma_M: [[17.51497282 17.51497282 17.51497282]
 [ 4.83069796  4.83069796  4.83069796]
 [ 4.25672557  4.25672557  4.25672557]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.36754234  4.36754234  4.36754234]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.28348662  4.28348662  4.28348662]
 [ 4.25034596  4.25034596  4.25034596]]
centers: [array([34.41804806, 56.66577354, 75.66265715]), array([ 1.01924049,  3.353453  ,  7.30611121, 10.68150533, 12.39466487]), array([0.00254684, 1.00492911]), array([1.92923445e-24, 1.00000000e+00, 3.00000000e+00]), array([0.00179591, 1.03027354]), array([3.86883971e-36, 1.00000000e+00, 3.00000000e+00]), array([0.00104623, 1.00973025]), array([8.08876680e-04, 1.00168886e+00]), array([3.3716418e-63, 1.0000000e+00]), array([1., 2., 3., 4., 5., 6.])]
Train finish :  4.557091951370239
/kaggle/working/data

Only Table Feature Remove Missing

In [30]:
FIS(fileName="Only Table Feature Replace Missing",
    filePath="/kaggle/input/datasetfile/OnlyTableFeatureReplaceMissing.csv",
    cluster=[2,2,5,5,3,2,2,2,2,2,2,3,5,3,3,2,3,2,3,2,2,2,6])

ruleList: [[1. 1. 3. ... 2. 2. 1.]
 [1. 1. 2. ... 1. 1. 3.]
 [1. 1. 2. ... 2. 2. 1.]
 ...
 [1. 1. 1. ... 2. 2. 1.]
 [2. 2. 2. ... 2. 2. 1.]
 [1. 1. 2. ... 1. 1. 3.]]
sigma_M: [[ 4.02616655  4.02616655  4.02616655]
 [ 3.8124749   3.8124749   3.8124749 ]
 [ 4.64231251  4.64231251  4.64231251]
 [ 4.63733994  4.63733994  4.63733994]
 [17.73736875 17.73736875 17.73736875]
 [ 3.47819036  3.47819036  3.47819036]
 [ 3.32071848  3.32071848  3.32071848]
 [ 3.35849137  3.35849137  3.35849137]
 [ 3.32963156  3.32963156  3.32963156]
 [ 3.52519878  3.52519878  3.52519878]
 [ 3.41547099  3.41547099  3.41547099]
 [ 8.42626983  8.42626983  8.42626983]
 [ 4.84370546  4.84370546  4.84370546]
 [32.83959655 32.83959655 32.83959655]
 [22.09808511 22.09808511 22.09808511]
 [ 4.25723952  4.25723952  4.25723952]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.37413403  4.37413403  4.37413403]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.29173597  4.29173597  4.29173597]
 [ 4.25025599  4.25025599  4.25025599]]
cente

Fusion Feature Remove Missing

In [31]:
FIS(fileName="Fusion Feature Remove Missing",
    filePath="/kaggle/input/datasetfile/FusionFeatureRemoveMissing.csv",
    cluster=[3,5,2,3,2,3,2,2,2,5,5,5,5,5,5,5,5,5,5,6])

ruleList: [[3. 4. 2. ... 1. 2. 3.]
 [3. 4. 1. ... 1. 2. 3.]
 [2. 4. 2. ... 1. 2. 1.]
 ...
 [3. 3. 2. ... 1. 2. 1.]
 [3. 4. 2. ... 1. 1. 3.]
 [2. 1. 2. ... 2. 5. 4.]]
sigma_M: [[17.42947947 17.42947947 17.42947947]
 [ 4.8681085   4.8681085   4.8681085 ]
 [ 4.25505109  4.25505109  4.25505109]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.3093938   4.3093938   4.3093938 ]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.28465209  4.28465209  4.28465209]
 [ 4.25024473  4.25024473  4.25024473]
 [ 4.246609    4.246609    4.246609  ]
 [ 2.92520872  2.92520872  2.92520872]
 [ 2.38801388  2.38801388  2.38801388]
 [ 2.43585685  2.43585685  2.43585685]
 [ 2.23437186  2.23437186  2.23437186]
 [ 2.60464959  2.60464959  2.60464959]
 [ 2.29612427  2.29612427  2.29612427]
 [ 2.21173811  2.21173811  2.21173811]
 [ 2.06706176  2.06706176  2.06706176]
 [ 2.47846749  2.47846749  2.47846749]]
centers: [array([34.80369271, 57.13811913, 75.84698034]), array([ 1.0172388 ,  3.4084139 ,  7.34989948, 10.68535332, 12.48

Fusion Feature Replace Missing

In [32]:
FIS(fileName="Fusion Feature Replace Missing",
    filePath="/kaggle/input/datasetfile/FusionFeatureReplaceMissing.csv",
    cluster = [2,2,3,3,3,2,2,2,2,2,2,3,3,3,3,2,3,2,3,2,2,2,5,5,5,5,5,5,5,5,5,5,6])

ruleList: [[1. 1. 1. ... 1. 2. 1.]
 [1. 1. 2. ... 2. 3. 4.]
 [1. 1. 2. ... 2. 4. 3.]
 ...
 [1. 1. 2. ... 2. 3. 5.]
 [1. 1. 2. ... 2. 4. 4.]
 [1. 1. 1. ... 1. 1. 1.]]
sigma_M: [[ 4.02962913  4.02962913  4.02962913]
 [ 3.8227353   3.8227353   3.8227353 ]
 [ 4.49510463  4.49510463  4.49510463]
 [ 4.44056495  4.44056495  4.44056495]
 [18.09026375 18.09026375 18.09026375]
 [ 3.49129484  3.49129484  3.49129484]
 [ 3.33897938  3.33897938  3.33897938]
 [ 3.37642623  3.37642623  3.37642623]
 [ 3.34741024  3.34741024  3.34741024]
 [ 3.52776884  3.52776884  3.52776884]
 [ 3.41950898  3.41950898  3.41950898]
 [ 8.49235008  8.49235008  8.49235008]
 [ 4.12478122  4.12478122  4.12478122]
 [32.5982273  32.5982273  32.5982273 ]
 [ 6.13929721  6.13929721  6.13929721]
 [ 4.25510822  4.25510822  4.25510822]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.33735259  4.33735259  4.33735259]
 [ 1.2739827   1.2739827   1.2739827 ]
 [ 4.28305377  4.28305377  4.28305377]
 [ 4.24841124  4.24841124  4.24841124]
 [ 4.2